redis:
  sentinel:
    master: REDIS_SENTINEL
    nodes: 112.74.170.75:16379,112.74.170.75:16380
  password: 
  timeout:   10000   # 链接超时时间（毫秒）
  pool:
    max-active: 50   # 最大连接数（负值表示没有限制）
    max-wait:   2000 # 最大阻塞等待时间（负值表示没有限制）
    max-idle:   20   # 最大空闲链接
    min-idle:   5    # 最小空闲链接
